### ISSUE TITLE
Find a way of generating the fields.json from schema.json

### ISSUE THREAD

**Issue by rowanwins** [stac-utils/stac-fields#17]
It seems that each extension has a `schema.json` file which contains lots of relevant information, eg https://github.com/stac-extensions/scientific/blob/main/json-schema/schema.json

I wonder if we could find a way to auto-magically populate the `fields.json` file with information from the relevant schemas, basically a script which would do it?

Perhaps it's more hassle than it's worth but it's an idea :)

**Comment by m-mohr** [comment]
That would be nice, but due to the complex nature of the schemas, this is likely to break in many cases that don't follow the template and thus it is likely easier to just maintain it manually. Also, the fields.json has additional data that is not present in the schemas so you'd actually need to extend all schemas upfront. So yeah, it sounds nice, but seems relatively unfeasible.
